### ISSUE TITLE
Trying to use gantryd with an existing cluster

### ISSUE THREAD

**Issue by luafran** [DevTable/gantryd#10]
Hi

This is my setup.

I have a CoreOS cluster running on AWS, the cluster is composed of 3 nodes running etcd and all of them have public IP.

I have my docker images hosted on quay.io.

I am running gantryd commands from my develpoment machine outside of cluster.

I am following the Getting Started guide in README.md and I am stuck while trying to run a component. I think this issue is related to IP address that I am not setting somewhere. How can I debug the issue?

Here you have some information that may help.

(docker)luafran@bart:~/work/docker/gantryd$ cat test.config 
{
  "components": [
    {
      "healthChecks": [
        {
          "kind": "http",
          "path": "/health",
          "port": 10001
        }
      ],
      "name": "tornado-service",
      "ports": [
        {
          "container": 10001,
          "external": 10001
        }
      ],
      "readyChecks": [
        {
          "kind": "http",
          "path": "/health",
          "port": 10001
        }
      ],
      "readyTimeout": 100000,
      "repo": "quay.io/luafran/tornado-service",
      "tag": "latest"
    }
  ]
}

(docker)luafran@bart:~/work/docker/gantryd$ ./gantryd.py -etcd 52.xxx setconfig testproject test.config Configuration updated

(docker)luafran@bart:~/work/docker/gantryd$ sudo ./gantryd.py -etcd 52.xxx update testproject -c tornado-service

(docker)luafran@bart:~/work/docker/gantryd$ sudo ./gantryd.py -etcd 52.xxx list testproject
COMPONENT            STATUS               IMAGE ID            
tornado-service      ready                d73d99d52fd9fe803188a8a657cb63b342b20a850b8692256ca7485eb8cf65f4

(docker)luafran@bart:~/work/docker/gantryd$ sudo ./gantryd.py -etcd 52.xxx run testproject -c tornado-service
Gantryd running
[tornado-service] Component tornado-service is not running; starting

(After a while...)

Checking HTTP address in container 46991065d5f4: http://:10001/health
[tornado-service] Health check failed
[tornado-service] Sleeping 3 second(s)...
[tornado-service] Running health check: http

core@ip-xxx ~ $ etcdctl ls --recursive
/gantryd
/gantryd/projects
/gantryd/projects/testproject
/gantryd/projects/testproject/config
/gantryd/projects/testproject/components
/gantryd/projects/testproject/components/tornado-service
/gantryd/projects/testproject/components/tornado-service/state
/gantryd/projects/testproject/machines
/gantryd/projects/testproject/machines/f7759a4c-267b-11e5-b0d8-56847afe9799
/gantryd/projects/testproject/machines/f7759a4c-267b-11e5-b0d8-56847afe9799/state

core@ip-172-31-27-229 ~ $ etcdctl get /gantryd/projects/testproject/components/tornado-service/state{"status":"updatefail","machine":"f7759a4c-267b-11e5-b0d8-56847afe9799"}

core@ip-xxx ~ $ etcdctl get /gantryd/projects/testproject/machines/f7759a4c-267b-11e5-b0d8-56847afe9799/state
{"status":"running","ip":"127.0.1.1","components":["tornado-service"]}

**Comment by josephschorr** [comment]
The healthchecking code needs to be fully specified. Currently, you're putting `/health`, which means gantry is checking the URL `http://:10001/health` (which obviously doesn't succeed).

**Comment by luafran** [comment]
Thanks for your help but that is not the case. If you check the code what is missing is the container IP

address = '%s://%s:%s' % (self.protocol, container_ip, container_port)
if self.config.hasExtraField('path'):
    address += self.config.getExtraField('path')

I think I am doing something completely wrong. After investigating some time I guess that I have to run gantryd somehow on each machine running docker daemon. The problem is that I don't know if that is feasible if daemons are running on CoreOS, I mean, how do I install required dependencies? May be should I run gantryd inside a container?

Regards

**Comment by josephschorr** [comment]
Yeah, that'd be the best approach. You'll need to mount in the Docker socket and run the container as privileged in order for it to command Docker, but it should work.
