### ISSUE TITLE
gantryd vs. fleet

### ISSUE THREAD

**Issue by huikang** [DevTable/gantryd#11]
Hi,
I have used fleet in my project because fleet manages containers pretty well with the systemd-like unit file, sidekick processes, etc. Now I found this gantryd tool which looks very interesting to me as it supports draining requests from the old containers. So my question is shall I move to gantryd from fleet to manage my containers? It looks like gantryd provdes more features than fleet. Thanks

**Comment by josephschorr** [comment]
Hi huikang,

It is really a matter of what you find important: `fleet` and `gantryd` are both lower level systems with different goals. If all you need are single instances of services behind a load balancer with draining, gantryd seems to be better for your solution. If you need more fine grain control, fleet would be better. If you need the features of both (but with much more complexity), I'd suggest checking out Kubernetes.

Hope this helps!

**Comment by huikang** [comment]
Hi, Joseph,
Thanks of your explanation. But I do not think kubernete has the feature of
draining requests. Correct?

- Hui

**Comment by josephschorr** [comment]
Hi Hui,

It isn't in the main branch yet (AFAIK), but I imagine it will get that support in the near future.
