### ISSUE TITLE
Add termination signal and termination/health checks that use "docker exec"

### ISSUE THREAD

**Issue by derosm2** [DevTable/gantryd#18]
Just starting to test out gantryd and seems like it'd be useful to configure commands that get executed inside a docker container. For example I'm trying to update a component and need to shut down an old container, but it has an open connection from an outside health check that doesn't time out. Ideally I'd be able exec in to the container and send a TERM signal and let it gracefully exit.

**Comment by josephschorr** [comment]
`docker stop` should send a TERM signal: https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/

gantry will first call that command, so you should be able to listen for the signal and gracefully exit.

**Comment by derosm2** [comment]
Looks like gantry waits for connections to drop before calling docker stop [(see code here)](https://github.com/DevTable/gantryd/blob/2fb0041c8bb58037f78a703661a5b4680858af17/runtime/manager.py#L161). Since I'm dealing with long running connections, I need to be able to gracefully shutdown nginx so that gantry can continue. Ideally there'd be a way to way to tell my container it's going to be shut down while the connection is still active.
