### ISSUE TITLE
How to run multiple containers for a component on a machine.

### ISSUE THREAD

**Issue by vishalchaudhary** [DevTable/gantryd#26]
We tried running multiple container for a component on a single machine, but couldn't figure out a way apart from creating multiple components for the same image. Is there something like:

sudo ./gantryd.py run myprojectname -c myimage **scale=4**
or
sudo ./gantryd.py run myprojectname -c **myimage myimage** (note: two container of the same component)
Currently if we run the second command it destroys the previous container and the number of containers running are still 1.

**Comment by josephschorr** [comment]
@vishalchaudhary: What is the use case for running multiple copies of the same container, with the same config, on the same machine?

**Comment by madhur** [comment]
Scaling microservices comes to my mind. `docker-compose` supports this with scale option
https://docs.docker.com/compose/reference/scale/

It would be great to have this feature in gantryd

**Comment by josephschorr** [comment]
@madhur: The recommendation would be to either give a second definition for it `myimage2` or to use a more complicated orchestration system such as Kubernetes. If someone wants to create a PR to allow for gantry to scale existing components, however, I'd be happy to accept it.

**Comment by vishalchaudhary** [comment]
@josephschorr You guys have already done a marvellous job, we will work upon it and see if we can come up with something meaningful.
