### ISSUE TITLE
how to add machines to an etcd cluster to be used by gantryd

### ISSUE THREAD

**Issue by oba11** [DevTable/gantryd#5]
Hi,

Thanks for the great tool and open-sourcing it as well.
I'm looking at a way of connecting gantryd to an etcd cluster to run some containers across a fleet of machines.
Is it possible register multiple machines to an etcd cluster (without etcd running locally on them) to be used by gantryd?

Thank you.

**Comment by josephschorr** [comment]
Hi oba11,

You can definitely used etcd without running it locally; you just need to point your etcd client to the remote cluster.

Thanks,
Joey

**Comment by oba11** [comment]
@josephschorr Thanks so much for the response. I was able to do that yesterday.
Which command can I use to add docker hosts to the etcd cluster so that when I `./gantryd.py run`, the container runs all the docker hosts

**Comment by josephschorr** [comment]
@oba11 https://coreos.com/docs/distributed-configuration/getting-started-with-etcd/ should get you started. Let me know if you have any additional questions and I can put you in touch with our etcd team

**Comment by oba11** [comment]
Hi @josephschorr, I already started playing around etcd and kind of stuck where I have some questions. Would be great if you can put me through your etcd team. My email [here](oba@obajobi.com).

Thanks.
