### ISSUE TITLE
What are steps to update component?

### ISSUE THREAD

**Issue by roonglit** [DevTable/gantryd#6]
Hi, 

I'm following your document and I'm able to run these commands in order:

1 ./gantryd.py setconfig "my project name" "configuration file"
2 ./gantryd.py update "my project name" -c "my component name"
3 ./gantryd.py run "my project name" -c "my component name"

and it seems Gantryd starts monitoring the container because there are log like:

Checking HTTP address in container 8bc73c619485: http://172.17.0.10:80/health (/health is my health check path)

I wonder if I have an update on the image, what would I need to run? What I tried is

1 Open another termnal, because the current one is being used by previous Gantryd
2 On the new terminal, I can call ./gantryd.py update "my project name" -c "my component name"

What I got is new image id, and I wait for a while. What I'm expecting is on the first terminal, Gantryd should be able to detect an update an try to start it up. Unfortunately, there is nothing change, it's still monitoring the same container. 

So, I need to run this command on my second terminal

1 ./gantryd.py run "my project name" -c "my component name"

And now, the new image is started and replaced the old one. However, I was expecting that the Gantryd in my first terminal would be stopped (since the container is stopped), but what I got is the Gantryd in my first terminal change to monitor the new container instead, and Gantryd on my second terminal is also monitoring the same container. Now, I got two Gantryd process doing the same thing. 

My questions are: 
1 Should I have only one Gantryd run at a time?
2 What did I do wrong which caused two Gantryd process doing the same thing?

**Comment by josephschorr** [comment]
`update` should indeed cause the first container to be changed, but only if the actually image in your registry has been updated. Otherwise, the component is treated as having not been updated.
