### ISSUE TITLE
Possible to use gantryd without it running containers for you?

### ISSUE THREAD

**Issue by lukebond** [DevTable/gantryd#7]
I have a platform for running Docker containers that does something similar with HAProxy to gantryd (http://paz.sh). I'm interested in using gantryd (at first glance) to replace the complex Confd/Etcd/HAProxy setup I currently have (it works, but it isn't very nice to maintain). But I don't want gantryd to run containers for me, monitor them, etc.

Is this possible? Or do you plan to break gantryd up into components that could support such a usecase?

Good job btw, it looks great.

**Comment by josephschorr** [comment]
Hi luke,

If gantryd wouldn't be running or monitoring the containers, what component would you be using?

Thanks,
Joey

**Comment by lukebond** [comment]
hi @josephschorr thanks for getting back to me.

let's say i already have my own platform for orchestrating and running containers, but i want to use gantryd to do the haproxy magic for me. in my case that platform is http://paz.sh and i already do something similar to what gantryd does with haproxy, but if someone else is doing it better than i'd prefer to re-use :) but it looks like i need gantryd to replace more of my existing stack than i'd currently like to. which is fine, but not exactly what i was after atm.

**Comment by josephschorr** [comment]
http://www.vulcanproxy.com/ might be what you're looking for: it is an etcd-backed proxy.

**Comment by lukebond** [comment]
Thanks but I wasn't comfortable with the SRV records requirement for Vulcan. 

Anyway, thanks for getting back to me and good job on gantryd, looks great.
